export const ProdDetailTooltip = {
    col1: 'Pricing reflects the sale of small "broken carton" quantities to contractors and facilities maintenance who are end-users of product.',
    col2: 'Pricing reflects purchases of a standard carton quantity.',
    col3: 'Pricing reflects the purchase of a quantity that is equal to or greater than the standard contractor package. Also known as the trade price or end-column price.',
    amp: 'Average Market Price is a national average derived from our trusted distributor partners.',
    list: 'Pricing reflects the purchase of a quantity that is equal to or greater than the standard contractor package.',
    uom: 'The quantity associated with the unit of measure (UOM).',
    resaleElectrical: 'A SUGGESTED resale price based on a calculation of the Column 3 price.',
    resalePlumbingMechanical: 'A SUGGESTED resale price based on a calculation of the List price.',
    uomQuantity: 'The quantity associated with the unit of measure (UOM).',
    tsCatalogCode: 'A catalog code created by Trade Service for Distributors. The code is widely by distributors in their ERP systems.',
    tsPik: "Trade Service's permanent and unique key to identify the product",
    commodityCode: 'A proprietary Trade Service generated identification number which identifies a group of like materials. The commodity code name correlates with the commodity code number.',
    issue: 'Represents the year and issue update number (YY-NN) of the last product pricing change.',
    issueDate: 'The date of the last product pricing change.',
    priceStatus: "(A) Active, (D) Discontinued, (U) Unlisted - The product was not found in the manufacturer's most recent pricing sheet, (POA) Price on Arrival.",
    changeSymbol: 'Indicates whether the product had a price increase + or price decrease - .',
    countryOfOrgigin: 'Country of Origin information is based on information provided by manufacturers. Trade Service has not independently verified this information and does not warrant its accuracy.',
    currency: 'The monetary currency associated with the product pricing.',
    gtin: 'Global Trade Identification number. It is a unique identifier, 14-digit number for products or services that are purchased and invoiced.',
};